// Code generated by "stringer -type=MoodState"; DO NOT EDIT

package socialmedia

import "fmt"

const _MoodStateName = "MoodStateNeutralMoodStateHappyMoodStateSadMoodStateAngryMoodStateHopefulMoodStateThrilledMoodStateBoredMoodStateShyMoodStateComicalMoodStateOnCloudNine"

var _MoodStateIndex = [...]uint8{0, 16, 30, 42, 56, 72, 89, 103, 115, 131, 151}

func (i MoodState) String() string {
	if i < 0 || i >= MoodState(len(_MoodStateIndex)-1) {
		return fmt.Sprintf("MoodState(%d)", i)
	}
	return _MoodStateName[_MoodStateIndex[i]:_MoodStateIndex[i+1]]
}
